### ISSUE TITLE
coverage customization

### ISSUE THREAD

**Issue by 4WGH** [Clinical-Genomics/chanjo-report#7]
![bild](https://user-images.githubusercontent.com/12525201/85689711-28f94180-b6d3-11ea-9fc7-3d4a6fffb559.png)

If I select show gene, nothing happens :(

I though the gene names shuould show in the coverage report, or does it mean something else?

**Comment by dnil** [comment]
It does, and also on random cases in the Solna instance of Scout?

<img width="879" alt="Screenshot 2020-06-25 at 11 04 44" src="https://user-images.githubusercontent.com/758570/85690433-db310900-b6d3-11ea-9845-6bdc0aba3b6a.png">
Instead of 
<img width="886" alt="Screenshot 2020-06-25 at 11 06 08" src="https://user-images.githubusercontent.com/758570/85690536-f7cd4100-b6d3-11ea-8203-e91222de1f1c.png">

**Comment by dnil** [comment]
Or are you thinking about https://github.com/robinandeer/chanjo-report/issues/30?
